# Generated by Django 4.2.17 on 2025-01-30 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jpllabcaszipperdata", "0002_archiver_solr_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="archiver",
            name="solr_url",
        ),
    ]
