# Generated by Django 4.2.18 on 2025-02-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jpllabcaszipperdata", "0003_remove_archiver_solr_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="archiver",
            name="max_zip_size",
            field=models.IntegerField(
                default=1,
                help_text="Maximum size of a ZIP file before balking",
            ),
        ),
    ]
