# Generated by Django 4.2.18 on 2025-02-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jpllabcaszipperdata", "0004_archiver_max_zip_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archiver",
            name="max_zip_size",
            field=models.FloatField(
                default=1.8,
                help_text="Maximum size of a ZIP file before balking, in gigabytes",
            ),
        ),
    ]
