# Generated by Django 4.2.18 on 2025-02-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jpllabcaszipperdata", "0005_alter_archiver_max_zip_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="archiver",
            name="from_email",
            field=models.EmailField(
                default="ic-data@jpl.nasa.gov",
                help_text='"From" email address for notification emails',
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="archiver",
            name="labcas_url",
            field=models.URLField(
                default="https://edrn-labcas.jpl.nasa.gov/",
                help_text="URL of LabCAS (inserted for convenience into notification emails)",
            ),
        ),
    ]
